name: Global Media Streamer - WOTL

on:
  workflow_dispatch:
  schedule:
    - cron: '43 19 * * *'

concurrency:
  group: wotl-logic
  cancel-in-progress: true

jobs:
  core-process:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write

    steps:
      - name: Authorization check
        run: |
          if [ "${{ github.repository_owner }}" != "jozmas" ]; then
            exit 1
          fi

      - name: Initialize environment
        uses: actions/checkout@v4

      - name: Component installation
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg curl

      - name: Resource allocation
        env:
          DROPBOX_URL: ${{ secrets.YT_WOTL_KEY }}
        run: |
          set +e
          rm -f video.mp4 || true
          curl -L "$DROPBOX_URL" -o "video.mp4"
          if [ ! -s "video.mp4" ]; then echo "Download failed!"; exit 1; fi
          set -e

      - name: Transmission start
        env:
          TARGET_KEY: ${{ secrets.YOUTUBE_STREAM_KEY_2 }} # OPRAVENÉ NA DVOJKU
        run: |
          ffmpeg -nostdin -re -stream_loop -1 -i video.mp4 \
          -map 0:v:0 -map 0:a:0 \
          -vf "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,format=yuv420p" \
          -r 30 \
          -c:v libx264 -preset ultrafast -tune film \
          -b:v 6000k -minrate 6000k -maxrate 6000k -bufsize 12000k \
          -g 60 -keyint_min 60 -sc_threshold 0 \
          -threads 1 -profile:v high -level 4.1 -bf 0 \
          -x264-params "nal-hrd=cbr:force-cfr=1" \
          -af "volume=0.2,aresample=44100" \
          -c:a aac -b:a 128k -ac 2 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/$TARGET_KEY"

      - name: System logging
        if: always()
        run: |
          git config --global user.name "system-bot"
          git config --global user.email "bot@internal.com"
          git pull origin main --rebase || true
          echo "WOTL Sync: $(date)" > last_run_word.txt
          git add last_run_word.txt
          git commit -m "system update $(date)" || true
          git push origin main || true
